### PR TITLE
Release 4.1.0

### PR DESCRIPTION
**Pull request by charettes**
Refs #400

### CODE REVIEW

**Comment by jezdez** [comment]
Could we have #462 in there as well?

**Comment by charettes** [comment]
Sure thing, :eyes:

**Comment by jezdez** [comment]
@charettes Once #462 is merged the version number is derived from the Git tag, not needed to be updated, using [setuptools_scm](https://pypi.org/project/setuptools-scm/). The rest of the release process stays the same.

**Comment by illing2005** [comment]
This should have been a new major version (5.0.0) because it has some breaking changes (like dropping django 2.1)
Took me quite some time to figure out why my CI/CD pipeline wasn't working anymore :wink:

**Pull request merged**
