### PR TITLE
Used isort to sort imports

### PR DESCRIPTION
**Pull request by smithdc1**
## Problem

Added isort to this project refs #402  

## Solution

- applied isort
- added to `tox` envs
- added to `travis.yml`
- added to `makefile`
- added note to contributing guide
- used black profile
- updated changelog

## Commandments

- [ ] Write PEP8 compliant code.
- [ ] Cover it with tests.
- [x] Update `CHANGES.rst` file to describe the changes, and quote according issue with `GH-<issue_number>`.
- [ ] Pay attention to backward compatibility, or if it breaks it, explain why.
- [x] Update documentation (if relevant).

### CODE REVIEW

**Comment by jezdez** [comment]
@smithdc1 Please resolve the merge conflict, I'm planning on working to port django-model-utils to GitHub Actions from Travis soon.

**Comment by smithdc1** [comment]
@hramezani can you review?

**Review by hramezani — APPROVED** [review]
LGTM! Thanks :+1:

**Comment by smithdc1** [comment]
I got myself in to the jazzband org. Just checking it's ok to merge my own prs once someone has approved?

**Comment by hramezani** [comment]
@smithdc1 Yes, I think it is OK

**Comment by jezdez** [comment]
> I got myself in to the jazzband org. Just checking it's ok to merge my own prs once someone has approved?

A code review from another member is usually the best way to be sure that the change is good to merge, the actual merge can happen by the author or reviewer once getting approval. That said, depending on the project (e.g. if it's a security senstive project such as pip-tools) sometimes the review by another member is a requirement for a merge and is enforced with a GitHub repository setting.

**Pull request merged**
