### PR TITLE
Document Django 3.0 enumeration types by 'Choices'

### PR DESCRIPTION
**Pull request by adamchainz**
Adding docs so others can discover enumeration types. Could also consider deprecating, at least when minimum supported Django is 3.0.

### CODE REVIEW

**Comment by auvipy** [comment]
thanks!

**Comment by adamchainz** [comment]
What about deprecating `Choices` at some point? Should I make an issue?

**Comment by auvipy** [comment]
I believe yes! that should be deprecated eventually

**Comment by adamchainz** [comment]
Made #422

**Pull request merged**
