### PR TITLE
Replace ugettext_lazy with gettext_lazy in test models to satisfy Django deprecation warning.

### PR DESCRIPTION
**Pull request by hramezani**
## Problem

Related to https://github.com/jazzband/django-model-utils/commit/6fba04ec4ff32b34cca61c6f1770ef6e81a40e2b.

## Solution

Explain the solution that has been implemented, and what has been changed.

## Commandments

- [ ] Write PEP8 compliant code.
- [ ] Cover it with tests.
- [ ] Update `CHANGES.rst` file to describe the changes, and quote according issue with `GH-<issue_number>`.
- [ ] Pay attention to backward compatibility, or if it breaks it, explain why.
- [ ] Update documentation (if relevant).

### CODE REVIEW

**Comment by fgs-dbudwin** [comment]
Very excited about this change!  It will greatly clean up the output of running our tests.  There hasn't been a release in 2020...and idea when this can be integrated and a new release made?

**Comment by hramezani** [comment]
@smithdc1 Do you have time to take a look at this?

**Review by smithdc1 — APPROVED** [review]
Yes. Looks good to me.

**Comment by hramezani** [comment]
Thansk @smithdc1

**Pull request merged**
