### PR TITLE
Postgres tests

### PR DESCRIPTION
**Pull request by schinckel**
Tests fail when run under postgres.

I'll try to narrow this down a bit more.

### CODE REVIEW

**Comment by romgar** [comment]
The main issues are about ordering. When sqlite/MySQL usually returns the results in the same order as their insertion (when no specific order is asked), PostgreSQL behaves differently, which can explains why tests relying on ordered items (in a list for example) fail on PostgreSQL.

It could be great to fix the conflicts and according failing tests. That's a quite old thread @schinckel, still interested in making this PR be merged?

**Comment by romgar** [comment]
@schinckel would you like to work again on it, or can we work on it based on your changes?

**Comment by schinckel** [comment]
Feel free to use my stuff: I'm not sure I'll have time to work on it right now.

**Comment by Natim** [comment]
Closing this, @romgar feel free to open a new PR if you want.

**Comment by Natim** [comment]
I just realized this has been implemented with https://github.com/jazzband/django-model-utils/commit/2cb773372dec28a6ef777663ae642a8198702cc9

**Pull request closed without merging**
