### PR TITLE
Implemented ability to lie about modified fields

### PR DESCRIPTION
**Pull request by kezabelle**
This would be a first stab at the changes I was describing in #109, to allow for manually setting the `modified` attributes of a `TimeStampedModel` (or, really, the fields backing that model)
- Are there any other Django API methods that need demonstrating?
- Changelog/docs would need updating.

### CODE REVIEW

**Comment by philippeluickx** [comment]
This would be great for testing purposes... anything blocking this PR?

**Comment by merwok** [comment]
I have copied this in my code in order to have fixed values for tests, it works well!

**Comment by RDIL** [comment]
@philippeluickx conflicts.

**Comment by rjschave** [comment]
This PR checks for a primary key to determine if the object had previously been saved.  If there's no primary key, it allows the modified date to be changed by the developer.

#319 checks for a primary key as well.  If there's no primary key, it sets the modified date to the created date.  This was merged to master.

In both cases there is no primary key and there is a modified date (either the default (now) or the overridden value provided by the developer.  I couldn't think of way to distinguish between the two without making other changes.

I added an __init__ method to the AutoLastModifiedField class and set the value to None.  This gives us the ability to check for three scenarios in the pre_save method:

- If no primary key and modified is None:
    - set the modified date to created (address the goal of #319)
- If no primary key and modified has value:
    - developer provided a value and wants to override the date (the goal of this PR)
- If primary key
    - object had previously been saved - just set modified to now

This does change behavior that others may depend on.  That is, modified will not have a default value (now) when the object is constructed.  The value will be set when pre_save is called.  Are there any concerns about this?

If there are no concerns I can put together the code and tests I developed while working on this.  Should I commit to this PR or start a new one (I'm new to contributing to open source)?

**Comment by auvipy** [comment]
you can introduce a new PR and ask me to review that :) definitely, you can take some code/motivation from old pr :)

**Comment by eraye1** [comment]
bump, can we get this in?  :)

**Comment by auvipy** [comment]
Plz rebase

**Comment by Natim** [comment]
Rebased in #388 388

**Comment by Natim** [comment]
Merged with https://github.com/jazzband/django-model-utils/commit/cfbea2ca89c0262a0576c926d5c525bd3315c6b5

**Pull request closed without merging**
