### PR TITLE
Added Python and Django supported versions to README.rst

### PR DESCRIPTION
**Pull request by hramezani**
Added Python and Django supported versions to README.rst

### CODE REVIEW

**Comment by hramezani** [comment]
@smithdc1 Do you have time to take a look at this?

**Review by smithdc1 — APPROVED** [review]
Could add the Django one as well?

**Comment by hramezani** [comment]
> Could add the Django one as well?

Thanks @smithdc1 . Django supported versions badge added.

**Review by smithdc1 — APPROVED** [review]
Thanks

**Pull request merged**
